name: Performance Test
on:
  workflow_dispatch:
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
